from django.urls import path
from . import views

urlpatterns=[
 path('health/',views.health), path('auth/csrf/',views.csrf), path('auth/register/request-otp/',views.register_request_otp),path('auth/register/verify/',views.register_verify),path('auth/login/',views.login_view),path('auth/google/',views.google_login),path('auth/password-reset/request-otp/',views.password_reset_request_otp),path('auth/password-reset/verify-otp/',views.password_reset_verify_otp),path('auth/password-reset/complete/',views.password_reset_complete),path('auth/refresh-token/',views.refresh_session),path('auth/logout/',views.logout_view),path('auth/me/',views.me),path('users/me/',views.me),path('users/me/change-password/',views.change_password),
 path('content/exams/',views.exam_list),path('content/exams/<slug:exam_slug>/',views.exam_detail),path('content/exams/<slug:exam_slug>/answers-transcripts/',views.exam_answer_transcript),path('content/exams/<slug:exam_slug>/parts/',views.exam_parts),path('content/exams/<slug:exam_slug>/parts/<int:part_number>/',views.part_detail),path('content/questions/<int:question_id>/',views.question_detail),path('content/practice/parts/',views.practice_part_list),path('content/practice/parts/<int:part_number>/questions/',views.practice_part_questions),path('content/practice/check/',views.practice_check_answers),
 path('vocabulary/topics/',views.topic_list),path('vocabulary/topics/<slug:slug>/',views.topic_detail),path('vocabulary/terms/',views.term_list),path('vocabulary/terms/<int:term_id>/',views.term_detail),
 path('dashboard/summary/',views.dashboard_summary),path('learning/streak/',views.study_streak),path('learning/progress/',views.learning_progress),path('learning/vocabulary-progress/',views.vocabulary_progress),
 path('learning/quizzes/',views.quiz_create),path('learning/quizzes/<int:attempt_id>/',views.quiz_detail),path('learning/quizzes/<int:attempt_id>/answers/',views.quiz_answer),path('learning/quizzes/<int:attempt_id>/submit/',views.quiz_submit),path('learning/quizzes/<int:attempt_id>/result/',views.quiz_result),path('learning/quizzes/history/',views.quiz_history),
 path('assessments/attempts/',views.attempt_create),path('assessments/attempts/<uuid:attempt_id>/',views.attempt_detail),path('assessments/attempts/<uuid:attempt_id>/start/',views.attempt_start),path('assessments/attempts/<uuid:attempt_id>/progress/',views.attempt_progress),path('assessments/attempts/<uuid:attempt_id>/answers/',views.attempt_answers),path('assessments/attempts/<uuid:attempt_id>/submit/',views.attempt_submit),path('assessments/attempts/<uuid:attempt_id>/abandon/',views.attempt_abandon),path('assessments/attempts/<uuid:attempt_id>/result/',views.attempt_result),path('assessments/attempts/<uuid:attempt_id>/review/',views.attempt_review),path('assessments/history/',views.assessment_history),
 path('knowledge/grammar/',views.grammar_list),path('knowledge/grammar/<int:note_id>/',views.grammar_detail),path('knowledge/part-tips/',views.tips_list),path('knowledge/articles/',views.articles_list),
]
