user nginx;
worker_processes auto;
error_log stderr warn;
pid /var/run/nginx.pid;
events { worker_connections 2048; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  client_max_body_size 30m;
  keepalive_timeout 65;
  map $status $log_level { ~^5 error; ~^4 warning; default info; }
  log_format docker escape=json '{"timestamp":"$time_iso8601","level":"$log_level","event":"http_access","service":"nginx","request_id":"$upstream_http_x_request_id","method":"$request_method","endpoint":"$uri","status_code":$status,"duration_seconds":$request_time}';
  access_log /dev/stdout docker;
  include /etc/nginx/conf.d/*.conf;
}
